# @package _global_

# specify here default training configuration
defaults:
  - server: default.yaml
  - hydra: default.yaml
  - model/encoder: trained_bi.yaml
  - retriever/dense: bi.yaml
  - data: serve.yaml
  - sentiment: serve.yaml

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: ${work_dir}/data/

# path to folder with sentiment
data_senti_dir: ${work_dir}/data_/

# pretty print config at the start of the run using Rich library
print_config: True
