_target_: server.connexion_aiohttp.ConnexionAioHttpApp

# app server network
app_host: 'localhost'
app_port: 51050

# api
specification_dir: openapi
api_files: ['dmlab.yaml']

# gpu
cuda_visible_devices: '0'

# process
process_title: 'dmlab API (DEV)'
